export const ADMIN_PAGES = [
  ["/admin", "Overview"],
  ["/admin/users", "Login credentials"],
  ["/admin/rbac", "RBAC"],
  ["/admin/organisation", "Organisation setup"],
  ["/admin/crew-budgets", "Crew budgets"],
  ["/admin/release-quarters", "Release quarters"],
  ["/admin/readiness-criteria", "Definition of Ready"],
  ["/admin/complexity-dimensions", "Complexity dimensions"],
  ["/admin/issue-mapping", "Issue mapping"],
  ["/admin/epic-mapping", "Epic mapping"],
  ["/admin/resource-mapping", "Resource mapping"],
  ["/admin/complexity-mapping", "Complexity mapping"],
  ["/admin/cost-mapping", "Location sprint rates"],
  ["/admin/team-cost-mapping", "Team sprint rates"],
  ["/admin/daily-rates", "Location daily rates"],
  ["/admin/estimation-config", "Estimation config"],
] as const;
