import type { EstimationConfig } from "./types";

/**
 * Default governed configuration derived from PRD v1.0.
 * Band boundaries, Dev/QA split coefficients and confidence cutovers are
 * not fully specified in the Excel source (not attached). See docs/decisions.
 */
export const DEFAULT_CONFIG: EstimationConfig = {
  versionId: "cfg-v2-excel-7-1",
  rateVersionId: "rate-v2-excel-7-1",
  complexityDimensions: [
    {
      id: "functional",
      name: "Functional / Business Complexity",
      description: "Breadth and difficulty of business behaviour being changed.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = trivial change; 5 = multi-domain business redesign.",
      active: true,
    },
    {
      id: "technical",
      name: "Technical Complexity",
      description: "Engineering difficulty inside the solution itself.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = well-known pattern; 5 = novel or high-risk implementation.",
      active: true,
    },
    {
      id: "integration",
      name: "Integration Complexity",
      description: "Number and difficulty of system integrations.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = none/local; 5 = many external systems with uncertain contracts.",
      active: true,
    },
    {
      id: "data",
      name: "Data Complexity",
      description: "Data model, migration and quality risk.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = no data change; 5 = large migration or poor-quality source data.",
      active: true,
    },
    {
      id: "qa",
      name: "QA / Regression Complexity",
      description: "Test surface, regression depth and environment effort.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = isolated unit tests; 5 = wide regression across critical journeys.",
      active: true,
    },
    {
      id: "nfr",
      name: "Non-Functional / Security / Performance Complexity",
      description: "NFR, security and performance burden.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = standard NFRs; 5 = stringent security or performance work.",
      active: true,
    },
    {
      id: "dependencies",
      name: "Dependencies",
      description: "External and internal delivery dependencies.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = independent; 5 = many unmanaged dependencies.",
      active: true,
    },
    {
      id: "environment",
      name: "Environment Complexity",
      description: "Environment provisioning and constraint risk.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = standard environments; 5 = scarce or highly constrained platforms.",
      active: true,
    },
    {
      id: "release",
      name: "Release Complexity",
      description: "Release, change and rollout difficulty.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = standard release; 5 = coordinated multi-system cutover.",
      active: true,
    },
    {
      id: "uncertainty",
      name: "Uncertainty / Requirements Clarity",
      description: "How poorly understood the change still is.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = crystal clear; 5 = discovery still required.",
      active: true,
    },
  ],
  complexityMappings: [
    {
      lower: 0,
      upper: 16,
      tshirt: "XS",
      complexity: "Very Low",
      governance: "READY",
      interpretation: "Trivial, well-understood change.",
    },
    {
      lower: 16,
      upper: 32,
      tshirt: "S",
      complexity: "Low",
      governance: "READY",
      interpretation: "Small, localised engineering change.",
    },
    {
      lower: 32,
      upper: 48,
      tshirt: "M",
      complexity: "Moderate",
      governance: "READY",
      interpretation: "Standard feature with contained risk.",
    },
    {
      lower: 48,
      upper: 64,
      tshirt: "L",
      complexity: "High",
      governance: "READY",
      interpretation: "Substantial change; watch duration against one sprint.",
    },
    {
      lower: 64,
      upper: 80,
      tshirt: "XL",
      complexity: "Very High",
      governance: "REVIEW",
      interpretation: "Large issue; review before committing to a single sprint.",
    },
    {
      lower: 80,
      upper: 100.01,
      tshirt: "XXL",
      complexity: "Extreme",
      governance: "SPLIT",
      interpretation: "Too large for a normal issue; split or treat as epic.",
    },
  ],
  complexityBands: [
    { tshirt: "XS", minInclusive: 0, maxExclusive: 0.16 },
    { tshirt: "S", minInclusive: 0.16, maxExclusive: 0.32 },
    { tshirt: "M", minInclusive: 0.32, maxExclusive: 0.48 },
    { tshirt: "L", minInclusive: 0.48, maxExclusive: 0.64 },
    { tshirt: "XL", minInclusive: 0.64, maxExclusive: 0.8 },
    { tshirt: "XXL", minInclusive: 0.8, maxExclusive: 1.0001 },
  ],
  issueMappings: [
    {
      tshirt: "XS",
      totalSp: 1,
      devSp: 0.7,
      qaSp: 0.3,
      devPd: 0.7,
      qaPd: 0.3,
      totalPd: 1,
      sprintRule: "Complete within 1 sprint",
      governance: "READY",
      notes: "Canonical automated XS. Valid Fibonacci Issue SP.",
    },
    {
      tshirt: "S",
      totalSp: 3,
      devSp: 2.1,
      qaSp: 0.9,
      devPd: 2.21,
      qaPd: 0.95,
      totalPd: 3.16,
      sprintRule: "Complete within 1 sprint",
      governance: "READY",
      notes: "Canonical automated S estimate. 2 SP remains valid for manual calibration only.",
    },
    {
      tshirt: "M",
      totalSp: 5,
      devSp: 3.5,
      qaSp: 1.5,
      devPd: 4.03,
      qaPd: 1.73,
      totalPd: 5.76,
      sprintRule: "Complete within 1 sprint",
      governance: "READY",
      notes: "Canonical automated M estimate.",
    },
    {
      tshirt: "L",
      totalSp: 8,
      devSp: 5.6,
      qaSp: 2.4,
      devPd: 7.28,
      qaPd: 3.12,
      totalPd: 10.4,
      sprintRule: "Complete within 1 sprint",
      governance: "READY",
      notes: "Canonical automated L estimate.",
    },
    {
      tshirt: "XL",
      totalSp: 13,
      devSp: 9.1,
      qaSp: 3.9,
      devPd: 13.65,
      qaPd: 5.85,
      totalPd: 19.5,
      sprintRule: "Review — may exceed 1 sprint",
      governance: "REVIEW",
      notes: "Large Issue; review threshold (13 SP).",
    },
    {
      tshirt: "XXL",
      totalSp: 21,
      devSp: 14.7,
      qaSp: 6.3,
      devPd: 25.73,
      qaPd: 11.03,
      totalPd: 36.76,
      sprintRule: "Split — not a single-sprint item",
      governance: "SPLIT",
      notes: "Split trigger; not intended as a normal single-sprint Issue.",
    },
  ],
  issueStoryPointMappings: [
    { tshirt: "XS", canonicalSp: 1, governance: "READY" },
    { tshirt: "S", canonicalSp: 3, governance: "READY" },
    { tshirt: "M", canonicalSp: 5, governance: "READY" },
    { tshirt: "L", canonicalSp: 8, governance: "READY" },
    { tshirt: "XL", canonicalSp: 13, governance: "REVIEW" },
    { tshirt: "XXL", canonicalSp: 21, governance: "SPLIT" },
  ],
  epicMappings: [
    {
      tshirt: "XS",
      romSp: 13,
      expectedStories: 2,
      devSp: 9.1,
      qaSp: 3.9,
      devPd: 9.1,
      qaPd: 3.9,
      totalPd: 13,
      governance: "PLAN",
      notes: "Small epic ROM; plan as a short slice of work.",
    },
    {
      tshirt: "S",
      romSp: 21,
      expectedStories: 3,
      devSp: 14.7,
      qaSp: 6.3,
      devPd: 15.44,
      qaPd: 6.62,
      totalPd: 22.06,
      governance: "PLAN",
      notes: "Compact epic; still expected to decompose into a few issues.",
    },
    {
      tshirt: "M",
      romSp: 40,
      expectedStories: 5,
      devSp: 28,
      qaSp: 12,
      devPd: 32.2,
      qaPd: 13.8,
      totalPd: 46,
      governance: "PLAN",
      notes: "Standard epic ROM.",
    },
    {
      tshirt: "L",
      romSp: 70,
      expectedStories: 8,
      devSp: 49,
      qaSp: 21,
      devPd: 63.7,
      qaPd: 27.3,
      totalPd: 91,
      governance: "PLAN",
      notes: "Large epic; confirm decomposition path.",
    },
    {
      tshirt: "XL",
      romSp: 120,
      expectedStories: 13,
      devSp: 84,
      qaSp: 36,
      devPd: 126,
      qaPd: 54,
      totalPd: 180,
      governance: "DECOMPOSE",
      notes: "Epic decomposition boundary (120 ROM SP).",
    },
    {
      tshirt: "XXL",
      romSp: 200,
      expectedStories: 21,
      devSp: 140,
      qaSp: 60,
      devPd: 245,
      qaPd: 105,
      totalPd: 350,
      governance: "SPLIT EPIC",
      notes: "Epic split / initiative boundary (200 ROM SP).",
    },
  ],
  epicRomMappings: [
    { tshirt: "XS", romSp: 13 },
    { tshirt: "S", romSp: 21 },
    { tshirt: "M", romSp: 40 },
    { tshirt: "L", romSp: 70 },
    { tshirt: "XL", romSp: 120 },
    { tshirt: "XXL", romSp: 200 },
  ],
  allowedIssueStoryPoints: [
    { sp: 1, tshirt: "XS", autoOutput: true, notes: "Valid Fibonacci Issue SP." },
    {
      sp: 2,
      tshirt: "S",
      autoOutput: false,
      notes: "Valid Fibonacci; manual/team calibration only. Automated S canonical output is 3.",
    },
    { sp: 3, tshirt: "S", autoOutput: true, notes: "Canonical automated S estimate." },
    { sp: 5, tshirt: "M", autoOutput: true, notes: "Canonical automated M estimate." },
    { sp: 8, tshirt: "L", autoOutput: true, notes: "Canonical automated L estimate." },
    { sp: 13, tshirt: "XL", autoOutput: true, notes: "Large Issue; review threshold." },
    {
      sp: 21,
      tshirt: "XXL",
      autoOutput: true,
      notes: "Split trigger; not intended as a normal single-sprint Issue.",
    },
  ],
  resourceLevels: [
    {
      id: "beginner",
      name: "Beginner",
      capacitySpPerSprint: 3,
      daysPerPoint: 3.33,
      definition: "Average throughput per resource in one 2-week sprint.",
      rule: "Applies to Dev & QA",
    },
    {
      id: "intermediate",
      name: "Intermediate",
      capacitySpPerSprint: 5,
      daysPerPoint: 2.0,
      definition: "Average throughput per resource in one 2-week sprint.",
      rule: "Applies to Dev & QA",
    },
    {
      id: "experienced",
      name: "Experienced",
      capacitySpPerSprint: 7,
      daysPerPoint: 1.43,
      definition: "Average throughput per resource in one 2-week sprint.",
      rule: "Applies to Dev & QA",
    },
    {
      id: "senior",
      name: "Senior",
      capacitySpPerSprint: 10,
      daysPerPoint: 1.0,
      definition: "Average throughput per resource in one 2-week sprint.",
      rule: "Applies to Dev & QA",
    },
  ],
  complexityMultipliers: {
    XS: 1.0,
    S: 1.05,
    M: 1.15,
    L: 1.3,
    XL: 1.5,
    XXL: 1.75,
  },
  costMappings: [
    { location: "India", costMethod: "Daily Rate (CHF / resource-day)", cost: 250, standardTeamSize: 6, currency: "CHF" },
    { location: "United Kingdom", costMethod: "Daily Rate (CHF / resource-day)", cost: 600, standardTeamSize: 6, currency: "CHF" },
    { location: "United States", costMethod: "Daily Rate (CHF / resource-day)", cost: 700, standardTeamSize: 6, currency: "CHF" },
    { location: "Switzerland", costMethod: "Daily Rate (CHF / resource-day)", cost: 900, standardTeamSize: 6, currency: "CHF" },
    { location: "Poland", costMethod: "Daily Rate (CHF / resource-day)", cost: 350, standardTeamSize: 6, currency: "CHF" },
    { location: "Singapore", costMethod: "Daily Rate (CHF / resource-day)", cost: 500, standardTeamSize: 6, currency: "CHF" },
  ],
  teamCostMappings: [
    { teamLocation: "India", teamName: "Vikings", costMethod: "Team Sprint Rate", cost: 15000, standardTeamSize: 6, currency: "CHF" },
    { teamLocation: "India", teamName: "Spartans", costMethod: "Team Sprint Rate", cost: 15000, standardTeamSize: 6, currency: "CHF" },
    { teamLocation: "India / Switzerland", teamName: "Centurions", costMethod: "Team Sprint Rate", cost: 34500, standardTeamSize: 6, currency: "CHF" },
    { teamLocation: "Switzerland", teamName: "Praetorians", costMethod: "Team Sprint Rate", cost: 54000, standardTeamSize: 6, currency: "CHF" },
  ],
  sprintWorkingDays: 10,
  aiMinPct: 0,
  aiMaxPct: 0.5,
  issueMaxRecommendedSprints: 1,
  issueReviewSp: 13,
  issueSplitSp: 21,
  epicDecomposeSp: 120,
  epicSplitSp: 200,
  fullTeamRateUtilisationWarning: 0.75,
  readinessDiscoveryMax: 0.4,
  readinessSpikeMax: 0.6,
  confidenceHighReadinessMin: 0.8,
  confidenceHighUncertaintyMax: 2,
  confidenceLowReadinessMax: 0.5,
  confidenceLowUncertaintyMin: 4,
  qaSplitBase: 0.12,
  qaSplitFromQaScore: 0.28,
  qaSplitFromNfrScore: 0.08,
  qaSplitMin: 0.15,
  qaSplitMax: 0.5,
};

export function hydrateConfig(raw: Partial<EstimationConfig> | null | undefined): EstimationConfig {
  const merged: EstimationConfig = { ...DEFAULT_CONFIG, ...(raw ?? {}) };
  if (!merged.complexityMappings?.length && merged.complexityBands?.length) {
    merged.complexityMappings = merged.complexityBands.map((b) => ({
      lower: b.minInclusive * 100,
      upper: b.maxExclusive * 100,
      tshirt: b.tshirt,
      complexity: b.tshirt,
      governance: "READY",
      interpretation: "",
    }));
  }
  if (merged.complexityMappings?.length) {
    merged.complexityBands = merged.complexityMappings.map((m) => ({
      tshirt: m.tshirt,
      minInclusive: m.lower / 100,
      maxExclusive: m.upper / 100,
    }));
  }
  if (merged.issueMappings?.length) {
    merged.issueStoryPointMappings = merged.issueMappings.map((m) => ({
      tshirt: m.tshirt,
      canonicalSp: m.totalSp,
      governance: m.governance,
    }));
  }
  if (merged.epicMappings?.length) {
    merged.epicRomMappings = merged.epicMappings.map((m) => ({
      tshirt: m.tshirt,
      romSp: m.romSp,
    }));
  }
  return merged;
}
