import type { EstimationConfig } from "./types";

/**
 * Default governed configuration derived from PRD v1.0.
 * Band boundaries, Dev/QA split coefficients and confidence cutovers are
 * not fully specified in the Excel source (not attached). See docs/decisions.
 */
export const DEFAULT_CONFIG: EstimationConfig = {
  versionId: "cfg-v1-prd-defaults",
  rateVersionId: "rate-v1-prd-defaults",
  complexityDimensions: [
    {
      id: "functional",
      name: "Functional / Business Complexity",
      description: "Breadth and difficulty of business behaviour being changed.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = trivial change; 5 = multi-domain business redesign.",
      active: true,
    },
    {
      id: "technical",
      name: "Technical Complexity",
      description: "Engineering difficulty inside the solution itself.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = well-known pattern; 5 = novel or high-risk implementation.",
      active: true,
    },
    {
      id: "integration",
      name: "Integration Complexity",
      description: "Number and difficulty of system integrations.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = none/local; 5 = many external systems with uncertain contracts.",
      active: true,
    },
    {
      id: "data",
      name: "Data Complexity",
      description: "Data model, migration and quality risk.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = no data change; 5 = large migration or poor-quality source data.",
      active: true,
    },
    {
      id: "qa",
      name: "QA / Regression Complexity",
      description: "Test surface, regression depth and environment effort.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = isolated unit tests; 5 = wide regression across critical journeys.",
      active: true,
    },
    {
      id: "nfr",
      name: "Non-Functional / Security / Performance Complexity",
      description: "NFR, security and performance burden.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = standard NFRs; 5 = stringent security or performance work.",
      active: true,
    },
    {
      id: "dependencies",
      name: "Dependencies",
      description: "External and internal delivery dependencies.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = independent; 5 = many unmanaged dependencies.",
      active: true,
    },
    {
      id: "environment",
      name: "Environment Complexity",
      description: "Environment provisioning and constraint risk.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = standard environments; 5 = scarce or highly constrained platforms.",
      active: true,
    },
    {
      id: "release",
      name: "Release Complexity",
      description: "Release, change and rollout difficulty.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = standard release; 5 = coordinated multi-system cutover.",
      active: true,
    },
    {
      id: "uncertainty",
      name: "Uncertainty / Requirements Clarity",
      description: "How poorly understood the change still is.",
      weight: 1,
      minScore: 1,
      maxScore: 5,
      guidance: "1 = crystal clear; 5 = discovery still required.",
      active: true,
    },
  ],
  complexityBands: [
    { tshirt: "XS", minInclusive: 0, maxExclusive: 0.16 },
    { tshirt: "S", minInclusive: 0.16, maxExclusive: 0.32 },
    { tshirt: "M", minInclusive: 0.32, maxExclusive: 0.48 },
    { tshirt: "L", minInclusive: 0.48, maxExclusive: 0.64 },
    { tshirt: "XL", minInclusive: 0.64, maxExclusive: 0.8 },
    { tshirt: "XXL", minInclusive: 0.8, maxExclusive: 1.0001 },
  ],
  issueStoryPointMappings: [
    { tshirt: "XS", canonicalSp: 1, governance: "READY" },
    { tshirt: "S", canonicalSp: 3, governance: "READY" },
    { tshirt: "M", canonicalSp: 5, governance: "READY" },
    { tshirt: "L", canonicalSp: 8, governance: "READY" },
    { tshirt: "XL", canonicalSp: 13, governance: "REVIEW" },
    { tshirt: "XXL", canonicalSp: 21, governance: "SPLIT" },
  ],
  epicRomMappings: [
    { tshirt: "XS", romSp: 13 },
    { tshirt: "S", romSp: 21 },
    { tshirt: "M", romSp: 40 },
    { tshirt: "L", romSp: 70 },
    { tshirt: "XL", romSp: 120 },
    { tshirt: "XXL", romSp: 200 },
  ],
  resourceLevels: [
    { id: "beginner", name: "Beginner", capacitySpPerSprint: 3, daysPerPoint: 3.33 },
    { id: "intermediate", name: "Intermediate", capacitySpPerSprint: 5, daysPerPoint: 2.0 },
    { id: "experienced", name: "Experienced", capacitySpPerSprint: 7, daysPerPoint: 1.43 },
    { id: "senior", name: "Senior", capacitySpPerSprint: 10, daysPerPoint: 1.0 },
  ],
  complexityMultipliers: {
    XS: 1.0,
    S: 1.05,
    M: 1.15,
    L: 1.3,
    XL: 1.5,
    XXL: 1.75,
  },
  sprintWorkingDays: 10,
  aiMinPct: 0,
  aiMaxPct: 0.5,
  issueMaxRecommendedSprints: 1,
  epicDecomposeSp: 120,
  epicSplitSp: 200,
  readinessDiscoveryMax: 0.4,
  readinessSpikeMax: 0.6,
  confidenceHighReadinessMin: 0.8,
  confidenceHighUncertaintyMax: 2,
  confidenceLowReadinessMax: 0.5,
  confidenceLowUncertaintyMin: 4,
  qaSplitBase: 0.12,
  qaSplitFromQaScore: 0.28,
  qaSplitFromNfrScore: 0.08,
  qaSplitMin: 0.15,
  qaSplitMax: 0.5,
};
